name: Deploy AI Telegram Bot 
 
on: 
  workflow_dispatch: 
  push: 
    branches: [ main ] 
 
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
 
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v4 
 
    - name: Set up Python 
      uses: actions/setup-python@v4 
      with: 
        python-version: '3.11' 
 
    - name: Install dependencies 
      run: pip install -r requirements.txt 
 
    - name: Run AI Bot 
      env: 
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} 
        AI_API_KEY: ${{ secrets.AI_API_KEY }} 
      run: python main.py 
